# Generated by Django 5.2.4 on 2025-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikeai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontext',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='usercontext',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
